@baseUrl = http://localhost:3000
@email = pikopikopon@example.com
@password = pikopikopon
@token = {{Signup.response.body.$.token}}
@refreshToken = {{Signup.response.body.$.refreshToken}}
###
### ===== Auth =====
###
# @name Signup
POST {{baseUrl}}/auth/signup/
Content-Type: application/json

{
  "name": "ピコピコぽん太郎",
  "email": "pikopikopon@example.com",
  "password": "pikopikopon"
}
###
# @name Login
POST {{baseUrl}}/auth/login/
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
###
# @name Logout
POST {{baseUrl}}/auth/logout/
###
# @name RefreshToken
GET {{baseUrl}}/auth/refresh/
Authorization: Bearer {{refreshToken}}
###
# @name GetCurrentUser
GET {{baseUrl}}/auth/user/
Authorization: Bearer {{token}}
###
### ===== User =====
###
# @name GetAllUsers
GET {{baseUrl}}/users/all/
###
# @name GetOneUser
GET {{baseUrl}}/users/1
###
### ===== Chat =====
###
# @name GetOneChat
GET {{baseUrl}}/chats/1
###
# @name CreateOneChat
POST {{baseUrl}}/chats/create/
Content-Type: application/json

{
  "tableId": 1,
  "userId": 1,
  "content": "ヤサイマシマシニンニクマシマシアブラマシマシ"
}
###
### ===== Building =====
###
# @name GetAllBuildings
GET {{baseUrl}}/buildings/all/
###
# @name GetOneBuilding
GET {{baseUrl}}/buildings/1
###
### ===== Room =====
###
# @name GetOneRoom
GET {{baseUrl}}/rooms/1
###
# @name GetRoomsByBuildingId
GET {{baseUrl}}/rooms/buildingId/1
###
# # @name GetRoomTables
# GET {{baseUrl}}/rooms/1/tables/
###
# # @name GetRoomActiveUsers
# GET {{baseUrl}}/rooms/1/users/
###
### ===== Table =====
###
# @name GetTableChats
GET {{baseUrl}}/tables/1/chats/
